name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.21"
          - "1.22"
          - "1.23"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go (${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build (${{ matrix.go }})
      run: go build ./...

    - name: Test (${{ matrix.go }})
      run: go test ./...
